from external_asset_ism_ismc_generation_tool.media_data_parser.media_box_extractor.box_type_relation import BoxTypeRelation
from external_asset_ism_ismc_generation_tool.media_data_parser.media_box_extractor.box_type_relation_map import BoxTypeRelationMap
from external_asset_ism_ismc_generation_tool.media_data_parser.media_box_extractor.media_box_extractor import MediaBoxExtractor
